In [3]:
# importing module

import numpy as np

### NumPy Array Methods and calculations

1. For creating a Placeholder Matrix

**np.zeros**
<pre>
arr=np.zeros((3,4))
</pre>
**np.ones**
<pre>
arr=np.ones((3,4))
</pre>

In [7]:
arr_zero=np.zeros((3,4))
print('Array with np.zeros:\n',arr_zero)

arr_ones=np.ones((3,4))
print('\nArray with np.ones:\n',arr_ones)

Array with np.zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Array with np.ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


2. You can use np.empty to create an uninitialized array of random data
<pre>
np.empty((2,3))
</pre>

In [8]:
arr_empty=np.empty((2,3))
print('Uninitialized array:\n',arr_empty)

Uninitialized array:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [53]:
arr_zero[0][1]=45
print(arr_zero)

[[ 0. 45.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [9]:
# You may select particular numbers in array

arr = np.array([10, 90, 30, 60, 40, 90, 70, 80, 50, 100])

print(arr[arr>50])  # will return only elements bigger than 50

[ 90  60  90  70  80 100]


In [10]:
# You may find even number and calculate power of 2 with each elemets in array 

arr = np.array([10, 95, 32, 16, 240, 19, 77, 50, 100])

print(arr[arr%2==0]**2)

[  100  1024   256 57600  2500 10000]


In [11]:
# You may add two elements from array

print(arr[2] + arr[3])

48


In [12]:
# You may even do calculations between two array elements

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

new_arr = arr1+arr2
print(new_arr)

[5 7 9]


### Data Type of array

* Every ndarray has an associated data type (dtype) object
*  it gives us information about :
  - Type of the data (integer, float, Python object etc.)
  - Size of the data (number of bytes)

*Note*- NumPy has some extra data types, and refer to data types with one character, like i for integers, s for string and u for unsigned integers etc.

|character|Data type|
|----|----|
|i| integer|
|b | boolean|
|u|unsigned integer|
|f |float|
|c| complex float|
|m | timedelta|
|M | datetime|
|O | object|
|S | string|

In [13]:
# dtype returns the data type of the array

arr.dtype

dtype('int32')

In [14]:
arr = np.array(['nissan', 'renolt', 'mazda', 'hundai'])

print(arr.dtype)

<U6


In [15]:
# you can also define data type while assigning array

arr = np.array([1, 2, 3, 4], dtype='f')   

print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float32


to change the data type of an existing array, we'll make a copy of the array with the astype() method

In [16]:
# A non integer string like 'a' can not be converted to integer, thus it will raise an error

arr = np.array(['a', '2', '3'])
sarr = arr.astype('i')

print(sarr)

ValueError: invalid literal for int() with base 10: 'a'

In [17]:
arr = np.array(['4', '2', '3'])
sarr = arr.astype('i')

print(sarr)
print(sarr.dtype)

[4 2 3]
int32


In [18]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [19]:
# you can write int and bool in place of 'i' etc.

arr = np.array([1.0, 0.5, 3.2])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 0 3]
int32


In [20]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


### View and Copy method

* the copy() is a new array, and the view() is just a view of the original array
* copy owns the data and any changes made to the copy will not affect original array and vice versa

In [21]:
# Let's make a copy of the array, change the original array, and display both arrays

arr = np.array([1, 2, 3, 4, 5])  # original array
copy_arr = arr.copy()   # creating a copy array

arr[0] = 10   # making changes in original array

print('Original array: ',arr)
print('Copied array: ',copy_arr)

Original array:  [10  2  3  4  5]
Copied array:  [1 2 3 4 5]


In [22]:
# Noe let's do the same with view method

arr = np.array([1, 2, 3, 4, 5])  # original array
new_arr = arr.view()   # creating an array for viewing

arr[0] = 10   # making changes in original array

print('Original array: ',arr)
print('Viewing array: ',new_arr)

Original array:  [10  2  3  4  5]
Viewing array:  [10  2  3  4  5]


* The view does not own the data and any changes made to the view will affect the original array
* any changes made to the original array will affect the view

In [23]:
# now if we make changes in view array

new_arr[2] = 20   # making changes in viewing array

print('Original array: ',arr)
print('Viewing array: ',new_arr)

Original array:  [10  2 20  4  5]
Viewing array:  [10  2 20  4  5]


* copies owns the data, and views does not own the data
------------------------------------------------------------------
attribute **base** returns None if the array owns the data, otherwise, it refers to the original object

In [24]:
print('Copied array : ',copy_arr.base)
print('Viewed array : ',new_arr.base)

Copied array :  None
Viewed array :  [10  2 20  4  5]


### Iterating array elements one by one

In [25]:
# Iterating 1D Arrays 

for item in copy_arr:
  print(item)

1
2
3
4
5


In [26]:
# Iterating 2D array

arr = np.array([[1, 2, 3], [4, 5, 6]])

for item in arr:
  print(item)

[1 2 3]
[4 5 6]


In [27]:
# To return the actual values, the scalars, we have to iterate the arrays in each dimension

for dimension in arr:
    for item in dimension:
        print(item)
    print('\n')

1
2
3


4
5
6




In [28]:
arr = np.array([[[1, 2, 3], [4, 5, 6]],[[7,8,9],[10,11,12]]])

for item in arr:
    print(item)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [29]:
for first_dimension in arr:
  for second_dim in first_dimension:
    for item in second_dim:
      print(item)
  print('\n')

1
2
3
4
5
6


7
8
9
10
11
12




* iterating through each scalar of an array we need to use n-for loops which can be difficult to write for arrays with very high dimensionality
* To make it easy there is a helping function **nditer()** that can be used from basic to advance iterations
--------------------------------------------------------------------------
syntax :
<pre>
numpy.nditer(array)
</pre>

In [30]:
for item in np.nditer(arr):
  print(item)

1
2
3
4
5
6
7
8
9
10
11
12


In [31]:
# iterate through every scalar element of multi-ndarray skipping 1 element

for x in np.nditer(arr[:, ::2]):
  print(x)

1
2
3
7
8
9


### Joining NumPy Arrays

We pass a sequence of arrays to join to the concatenate() function, along with the axis
<pre>
np.concatenate((arr1, arr2))
</pre>

In [32]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [33]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)  # Join two 2-D arrays along rows (axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


Stacking is same as concatenation, the only difference is that stacking is done along a new axis, so if we concatenate two 1-D arrays, the result will be in one over the other, ie. stacking

In [34]:
arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [35]:
# hstack() to stack along rows

arr = np.hstack((arr1, arr2))

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [36]:
# vstack()  to stack along columns

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [37]:
# dstack() to stack along height, which is the same as depth

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


Splitting breaks one array into multiple. **array_split()** is used for splitting arrays, and the arguments it takes are, the array we want to split and the number of splits

In [38]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [39]:
newarr1 = np.array_split(arr, 4)  # If the array has less elements than required spilt number, it will adjust array size accordingly
print(newarr1)

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


In [40]:
# splitiing 2D arrays

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 4)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10]]), array([[11, 12]])]


In [41]:
# Split the 2-D array into three 2-D arrays along rows

newarr = np.array_split(arr, 2, axis=1)
print(newarr)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]])]


In [42]:
# hsplit() method will do the same 

newarr = np.hsplit(arr,2)  # to split the 2-D array into three 2-D arrays along rows
print(newarr)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]])]


In [43]:
newarr = np.vsplit(arr,2)
print(newarr)

[array([[1, 2],
       [3, 4],
       [5, 6]]), array([[ 7,  8],
       [ 9, 10],
       [11, 12]])]


In [44]:
# where() method is used to search an array for a certain value, and return the indexes that get a match

arr = np.array([1, 2, 3, 4, 5, 4, 4])

match = np.where(arr == 4)
print(match)


(array([3, 5, 6], dtype=int64),)


In [45]:
# sort() method is used to sort a specified array

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [46]:
# multi dimensional array

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
